### ISSUE TITLE
Separate images for voice activity on and off

### ISSUE THREAD

**Issue by Boundarybreaker** [Fugiman/discord-reactive-images#24]
A lot of streamers like to use separate images to indicate when they're talking or not, instead of using a dimmer. It adds a bit more life to the image. Right now, the system only uses one image that dims when inactive. Would it be possible to add a way to to have separate active and inactive images instead of dimming?

**Comment by Fugiman** [comment]
yes, i'll work on that!

**Comment by Fugiman** [comment]
Apologies it took so long, but this is now implemented :)

**Comment by Boundarybreaker** [comment]
Thank you so much!!
