### ISSUE TITLE
Include ability to "hide" your own avatar

### ISSUE THREAD

**Issue by uujfwmnp** [Fugiman/discord-reactive-images#32]
For people using a Live2D/3D avatar, they might want to not have their own Discord image shown. While a workaround can be to upload a blank/transparent png image, it might be easier if the user could simply choose to hide their avatar, so it doesn't appear in the OBS overlay.

**Comment by Fugiman** [comment]
Uncheck "Include Self" on https://discord-reactive-images.fugi.tech/manage
