### ISSUE TITLE
Background is not transparent

### ISSUE THREAD

**Issue by TheR-Man** [Fugiman/discord-reactive-images#46]
There's currently a problem with the background of the browser source.
Instead of being transparent(like before the new version) it now shows a black/grey-ish background (see screenshot)
![image](https://user-images.githubusercontent.com/43365763/116567207-b4e98480-a907-11eb-9ad6-a1227bc942ca.png)

**Comment by Fugiman** [comment]
This should now be fixed, thanks so much for reporting it!
