### ISSUE TITLE
Background not transparent

### ISSUE THREAD

**Issue by Boundarybreaker** [Fugiman/discord-reactive-images#49]
![image](https://user-images.githubusercontent.com/6722691/116834196-d2ba2200-ab71-11eb-85ae-1ae86c9aa08d.png)

For some reason the background for the reactive image system has become opaque, and cannot easily be hidden.

**Comment by Fugiman** [comment]
Should be fixed now, sorry about that and thank you for the report

**Comment by Boundarybreaker** [comment]
it is fixed indeed! thank you so much

**Comment by orribu** [comment]
Heya, I'd hate to resurrect the dead here but I've encountered this same issue recently! I tested it in both OBS and XSplit and I'm unsure if I'm doing anything wrong! ;-;
