### ISSUE TITLE
Group and Individual links don't work in Streamlabs OBS

### ISSUE THREAD

**Issue by JesterSaysYeet** [Fugiman/discord-reactive-images#55]
While attempting to use Discord Reactive Images, neither of the links provided to create the browser source work in Streamlabs OBS. The source is blank until the URL is just the Reactive Images website URL, where it shows the main page gif and nothing else. I'm not sure if this is a problem with just Streamlabs or if it's an issue with Reactive Images.

**Comment by Fugiman** [comment]
The links will only show something if you are in a discord voice call, otherwise they will be blank. Please verify that you're in a voice call, that the URLs work inside your browser, and do NOT work in SLOBS.
