### ISSUE TITLE
Options to turn off the dimming effect on the inactive image

### ISSUE THREAD

**Issue by Macckks** [Fugiman/discord-reactive-images#60]
Hey! I really love your invention!!!
But one thing that kind of bothers me nonetheless, is the fact that I cannot turn off the dimming on the inactive image. Is it possible to maybe have a setting that can turn it off? 

Thanks!

**Comment by katubug** [comment]
Hi! I just started using the program, and I agree, I would really like this feature! I'm doing a use case where the inactive image has a closed mouth and the active one has an open mouth, so the dimming isn't really necessary for me.

**Comment by Fugiman** [comment]
This is now supported, thanks for the request!
