### ISSUE TITLE
Background Transparency Doesn't Work

### ISSUE THREAD

**Issue by orribu** [Fugiman/discord-reactive-images#72]
Heya, I'd hate to resurrect the dead here, but I noticed that the background isn't transparent! The only way I could fix the issue was to add the following CSS to the element:

`body { background-color: rgba(0, 0, 0, 0); margin: 0px auto; overflow: hidden; }`

I tested this in both XSplit 4.2 and OBS 27.1.3.
I'm running Windows 10, 64-bit, and I'm running Discord Stable 105691 (039634f).

**Comment by Fugiman** [comment]
Yes, I assume that everyone is using the default CSS for OBS browser sources, which includes `body { background-color: rgba(0, 0, 0, 0); }`

v3 (coming soon) will remove this assumption

**Comment by orribu** [comment]
Ohh, okay! :0
I realized that the default background CSS wasn't in XSplit but it was in OBS! I'm vaguely aware of CSS, still learning myself.
But thanks so much!
