### ISSUE TITLE
APNG Compatibility?

### ISSUE THREAD

**Issue by orribu** [Fugiman/discord-reactive-images#73]
Hey there, this isn't an issue as much as it's a question. First off, thank you so much for making this tool! It will be far easier to manage my reactive images! I wanted to know if there would be compatibility for animated PNGs sometime in the future? I'd go with gifs, but they are really hit-and-miss, especially with transparent backgrounds and the color distortion. 
I tried uploading my animated PNG images, but it doesn't look like the images were successfully uploaded. 
Thank you ahead of time for your consideration and help!

**Comment by Fugiman** [comment]
Heya, sorry I have no plans to ever support APNG. Gif support will be coming soon and will be the only supported method of animation.

**Comment by orribu** [comment]
Oh, hey! No problem at all! I totally understand! ;v; /
Thanks for your time!
