### ISSUE TITLE
Transparent image while reacting

### ISSUE THREAD

**Issue by AriixIT** [Fugiman/discord-reactive-images#87]
When my image changes between the two states, it shortly appears to be slightly transparent, making it look very weird. How can I fix this?
![image](https://user-images.githubusercontent.com/49060231/147984530-7820e018-3ca2-4eab-86fe-c44e87d94370.png)
![image](https://user-images.githubusercontent.com/49060231/147984584-f6aabc16-b019-406f-87ed-0b9533f226ee.png)

**Comment by Fugiman** [comment]
Use v3 https://reactive.fugi.tech
