### ISSUE TITLE
Transparent Image with Black BG in Streamlabs

### ISSUE THREAD

**Issue by infernalSage** [Fugiman/discord-reactive-images#88]
The images I uploaded had transparent backgrounds, but when loaded into Streamlabs it comes up with a black background instead of transparent.

Issue in Streamlabs:
![image](https://user-images.githubusercontent.com/98088233/150314903-3585d80c-06e0-4fa5-aed4-9e6f37563ce1.png)

Original File in website:
![image](https://user-images.githubusercontent.com/98088233/150314950-38ca4ddf-84ef-439f-9ad1-ae47279c6b1f.png)

**Comment by infernalSage** [comment]
after a bit, the black screen took over the image completely. closing streamlabs and leaving it closed for a bit did something-- had to wait a few minutes or it wouldnt reset, but it reset after waiting. no longer an issue.

**Comment by victor-zayas** [comment]
have de same problen with OBS, I close it and waited half an hour, the black bg still there
![imagen_2022-02-10_232449](https://user-images.githubusercontent.com/55438812/153506913-1a9c22af-05ca-41e8-aa71-02124179df08.png)

**Comment by Fugiman** [comment]
by default, OBS Studio includes a line of custom CSS when you add a browser source. You need to leave this line of CSS in, or add it back if you removed it. The CSS is body `{ background-color: rgba(0, 0, 0, 0); margin: 0px auto; overflow: hidden; }`

**Comment by victor-zayas** [comment]
Oh, thank you ^^, sry about that.
