### ISSUE TITLE
Image cuts off no matter how I change it

### ISSUE THREAD

**Issue by orbsnart** [Fugiman/discord-reactive-images#90]
I'm trying to use an image but no matter what I do to it, scaling it, cropping it to just the non-transparent portion, changing the aspect ratio, even adding a background to it, the edges get cropped off. In pretty much the exact same way too. This doesn't happen to other images I upload.
![ex-1](https://user-images.githubusercontent.com/99053133/152612974-bc590c38-c46a-46e9-bf03-6701dda30326.jpg)
![ex-2](https://user-images.githubusercontent.com/99053133/152612972-246b4fb9-a052-4ac2-ab38-29980436bd02.jpg)
![ex-3](https://user-images.githubusercontent.com/99053133/152612970-71072d71-c53a-4794-a0c0-1b5ffbe135c8.jpg)
![ex-4](https://user-images.githubusercontent.com/99053133/152612969-c4682490-adb8-48ab-9ec4-f80942496392.jpg)
![ex-5](https://user-images.githubusercontent.com/99053133/152612964-9ea4c62c-50dc-43d1-9535-2b96191e1d23.jpg)

**Comment by Fugiman** [comment]
Use v3 to avoid the auto-cropping https://reactive.fugi.tech
